"""Exercise real HTTP authentication and Git smart-HTTP publication on loopback.

HTTPS is rewritten to HTTP only for this local fixture, retaining the username
and password generated by the Action. No public Git server is contacted.
This host-side suite requires Python 3 and Git's http-backend; it is separate
from the network-disabled Docker publication suite.
"""

import base64
import gzip
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import subprocess
import sys
import threading
import unittest
from urllib.parse import urlsplit

# Import shared fixtures without leaving bytecode in the repository.
sys.dont_write_bytecode = True
import test_publish as publication


class GitHttpHandler(BaseHTTPRequestHandler):
    """Require Basic credentials, then pass local Git requests to http-backend."""

    def do_GET(self):
        self.serve_git()

    def do_POST(self):
        self.serve_git()

    def serve_git(self):
        if self.headers.get("Authorization") != self.server.authorization:
            self.send_response(401)
            self.send_header("WWW-Authenticate", 'Basic realm="local Git fixture"')
            self.send_header("Content-Length", "0")
            self.end_headers()
            return
        self.server.authenticated_requests += 1
        url = urlsplit(self.path)
        request = self.rfile.read(int(self.headers.get("Content-Length", "0")))
        if self.headers.get("Content-Encoding") == "gzip":
            request = gzip.decompress(request)
        env = self.server.git_env | {
            "GIT_PROJECT_ROOT": str(self.server.repository.parent),
            "GIT_HTTP_EXPORT_ALL": "1",
            "PATH_INFO": url.path,
            "QUERY_STRING": url.query,
            "REQUEST_METHOD": self.command,
            "CONTENT_TYPE": self.headers.get("Content-Type", ""),
            "CONTENT_LENGTH": str(len(request)),
            "SERVER_PROTOCOL": self.request_version,
            "REMOTE_ADDR": "127.0.0.1",
            "REMOTE_USER": "local-fixture",
        }
        result = subprocess.run(
            ["git", "http-backend"], input=request, env=env,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=15,
        )
        if result.returncode:
            self.send_error(500, "Git http-backend failed")
            return
        headers, body = result.stdout.split(b"\r\n\r\n", 1)
        parsed = [line.decode("latin-1").split(":", 1) for line in headers.split(b"\r\n")]
        status = next((int(value.strip().split()[0]) for key, value in parsed if key.lower() == "status"), 200)
        self.send_response(status)
        for key, value in parsed:
            if key.lower() != "status":
                self.send_header(key, value.strip())
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *args):
        # Never log fixture credentials or request headers.
        pass


class AuthenticationTests(unittest.TestCase):
    def setUp(self):
        self.fixture = publication.PublishTests()
        self.addCleanup(self.fixture.doCleanups)
        self.fixture.setUp()
        self.fixture.git("--git-dir", str(self.fixture.remote), "config", "http.receivepack", "true")
        self.fixture.git("config", "--global", "url.http://.insteadOf", "https://")
        self.server = ThreadingHTTPServer(("127.0.0.1", 0), GitHttpHandler)
        self.server.repository = self.fixture.remote
        self.server.git_env = self.fixture.env
        self.server.authenticated_requests = 0
        self.server.authorization = ""
        self.addCleanup(self.server.server_close)
        self.thread = threading.Thread(target=self.server.serve_forever, daemon=True)
        self.thread.start()
        self.addCleanup(self.thread.join, 5)
        self.addCleanup(self.server.shutdown)

    def authorize(self, credentials):
        self.server.authorization = "Basic " + base64.b64encode(credentials.encode()).decode()
        self.server.authenticated_requests = 0

    def test_tokens_explicit_credentials_and_pat_precedence_publish_over_http(self):
        cases = [
            (publication.TOKEN, "", f"x-access-token:{publication.TOKEN}"),
            ("", "raw-pat-never-log", "x-access-token:raw-pat-never-log"),
            ("", publication.PAT, publication.PAT),
            (publication.TOKEN, publication.PAT, publication.PAT),
        ]
        for index, (token, pat, credentials) in enumerate(cases):
            with self.subTest(case=index):
                self.authorize(credentials)
                content = f"authenticated publication {index}\n"
                (self.fixture.source / "artifact.txt").write_text(content)
                log, values = self.fixture.run_action(
                    host=f"127.0.0.1:{self.server.server_port}", repository="destination",
                    github_token=token, github_pat=pat, env_changes={"INPUT_REMOTE": None},
                )
                self.assertGreater(self.server.authenticated_requests, 0)
                self.assertEqual(values["commit_hash"], self.fixture.remote_hash())
                self.assertEqual(self.fixture.remote_text("artifact.txt"), content.strip())
                if pat:
                    self.assertNotIn(pat, log)
                self.assertNotIn(credentials.split(":", 1)[1], log)

    def test_rejected_http_credentials_do_not_create_a_branch(self):
        self.authorize("different-user:different-password")
        log, _ = self.fixture.run_action(
            expected=1, host=f"127.0.0.1:{self.server.server_port}", repository="destination",
            github_pat=publication.PAT, env_changes={"INPUT_REMOTE": None},
        )
        self.assertNotIn("test-user", log)
        self.assertEqual(self.server.authenticated_requests, 0)
        self.assertEqual(self.fixture.git("--git-dir", str(self.fixture.remote), "for-each-ref", "refs/heads"), "")


if __name__ == "__main__":
    unittest.main(verbosity=2)
